-- Initialize PostgreSQL database for showroom sales data
-- Run this file with:
--   psql -U postgres -h localhost -f db/init_showroom_sales.sql

-- 1) Create database (skip if you already created it in Python)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_database WHERE datname = 'showroom_sales'
  ) THEN
    PERFORM dblink_exec('dbname=' || current_database(),
                        'CREATE DATABASE showroom_sales');
  END IF;
END$$;

\connect showroom_sales;

-- 2) Core tables based on database_schema.md

-- Table: gofrugal_sales
CREATE TABLE IF NOT EXISTS gofrugal_sales (
  outlet_name      TEXT,
  bill_no          TEXT,
  bill_date        TIMESTAMP,
  net_amount       DOUBLE PRECISION,
  transaction_type TEXT,
  salesman         TEXT,
  source_file      TEXT
);

-- Table: gofrugal_item_mapping
CREATE TABLE IF NOT EXISTS gofrugal_item_mapping (
  dynamic_code TEXT,
  item_alias   TEXT,
  item_code    TEXT
);

-- Table: employee_targets
CREATE TABLE IF NOT EXISTS employee_targets (
  employee_id   TEXT,
  employee_name TEXT,
  target_amount DOUBLE PRECISION,
  target_date   TIMESTAMP
);

-- Table: gofrugal_outlets_mapping
CREATE TABLE IF NOT EXISTS gofrugal_outlets_mapping (
  outlet_name   TEXT,
  area_manager  TEXT,
  outlet_type   TEXT,
  dynamic_number TEXT,
  city          TEXT
);

-- Table: gofrugal_targets
CREATE TABLE IF NOT EXISTS gofrugal_targets (
  outlet_name    TEXT,
  target_date    TIMESTAMP,
  target_amount  BIGINT,
  year           BIGINT,
  month          BIGINT
);

-- Table: gofrugal_visitors
CREATE TABLE IF NOT EXISTS gofrugal_visitors (
  outlet_name   TEXT,
  visit_date    TIMESTAMP,
  visitor_count BIGINT
);

-- Table: product_category_rules
CREATE TABLE IF NOT EXISTS product_category_rules (
  prefix_pattern TEXT,
  category_name  TEXT
);

-- Table: gofrugal_employee_mapping
CREATE TABLE IF NOT EXISTS gofrugal_employee_mapping (
  employee_id  TEXT,
  sales_group  TEXT,
  arabic_name  TEXT
);

-- Table: calendar_events
CREATE TABLE IF NOT EXISTS calendar_events (
  event_name  TEXT,
  year        BIGINT,
  start_date  TIMESTAMP,
  end_date    TIMESTAMP,
  description TEXT
);

-- Table: gofrugal_item_sales
CREATE TABLE IF NOT EXISTS gofrugal_item_sales (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  outlet_name     TEXT,
  transaction_type TEXT,
  bill_no         TEXT,
  bill_date       TIMESTAMP,
  item_code       TEXT,
  item_name       TEXT,
  quantity        INTEGER,
  net_amount      NUMERIC,
  salesman_name   TEXT,
  ref_bill_no     TEXT,
  source_file     TEXT,
  created_at      TIMESTAMP DEFAULT now()
);

-- Table: dynamic_sales_bills (structure only for now – dynamic logic later)
CREATE TABLE IF NOT EXISTS dynamic_sales_bills (
  "@odata.etag"    TEXT,
  store_number     TEXT,
  bill_date        DATE,
  payment_amount   DOUBLE PRECISION,
  transaction_id   TEXT,
  item_lines_count BIGINT
);

-- Table: dynamic_sales_items (structure only for now – dynamic logic later)
CREATE TABLE IF NOT EXISTS dynamic_sales_items (
  "@odata.etag"      TEXT,
  store_number       TEXT,
  transaction_id     TEXT,
  sales_group        TEXT,
  net_amount         DOUBLE PRECISION,
  quantity           BIGINT,
  transaction_status TEXT,
  item_date          DATE,
  item_id            TEXT
);

-- Table: all_products
CREATE TABLE IF NOT EXISTS all_products (
  "@odata.etag"  TEXT,
  product_number TEXT,
  product_name   TEXT
);

-- Basic indexes to speed up analytics queries
CREATE INDEX IF NOT EXISTS idx_gofrugal_sales_bill_date
  ON gofrugal_sales (bill_date);

CREATE INDEX IF NOT EXISTS idx_gofrugal_sales_outlet
  ON gofrugal_sales (outlet_name);

CREATE INDEX IF NOT EXISTS idx_gofrugal_item_sales_bill_date
  ON gofrugal_item_sales (bill_date);

CREATE INDEX IF NOT EXISTS idx_gofrugal_item_sales_outlet
  ON gofrugal_item_sales (outlet_name);

CREATE INDEX IF NOT EXISTS idx_gofrugal_visitors_visit_date
  ON gofrugal_visitors (visit_date);

CREATE INDEX IF NOT EXISTS idx_gofrugal_targets_year_month
  ON gofrugal_targets (year, month);

